services:
  - type: web
    name: hr-analytics-dashboard
    env: static
    buildCommand: pnpm install && pnpm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: "18"